language: node_js
node_js:
    - "7"
script: 
    - npm run build
    - npm run test
after_script:
    - npm install codeclimate-test-reporter -g
    - codeclimate-test-reporter < **/*lcov.info
deploy:
  provider: npm
  email: fragezeichen@outlook.com
  api_key: $TOKEN
